services:
 - docker

language: minimal

jobs:
  include:
  - name: prod_image
    env: NODE_ENV=prod
    dist: bionic

branches:
  only:
  - master

before_install:
 - docker build -t mikajel/toybox .
